# Generated by tf-migrate 1.3.0


# Note on stacks authentication:
# tf-migrate cannot generate stack authentication, this needs to be manually added before execute
# More on authentication - https://developer.hashicorp.com/terraform/language/stacks/deploy/authenticate


store "varset" "tokens" {
  id       = "varset-SxmWGcgJQ5ac6BC7"
  category = "env"
}


deployment "prod-arena" {
  inputs = {
    bucket_name = "bucket-for-pikachu-vcs-v2"
    environment = "prod"
    access_key    = store.varset.tokens.AWS_ACCESS_KEY_ID
    secret_key    = store.varset.tokens.AWS_SECRET_ACCESS_KEY
    session_token = store.varset.tokens.AWS_SESSION_TOKEN
    tags = {
      Lvl     = 1
      Owner   = "skj-skj"
      Project = "tf-migrage-bugbash"
    }
  }
  # import = true
}

